/**
 * Mock data for development and UI preview.
 * Replace with real SQLite + service layer in production.
 */

import type { Identity }             from '../models/identity';
import type { Credential, Issuer, CredentialWithIssuer } from '../models/credential';

// ─── Mock identity ────────────────────────────────────────────────────────────

export const MOCK_IDENTITY: Identity = {
  did:    'did:sov:7Tq3kTmNpL8vXoAe9fP2Yz',
  alias:  'Sovereign.me',
  hardwareKey: {
    fingerprint:     'A3:4F:2B:9C:E1:7D',
    keyId:           'com.sovereigntrust.key.primary',
    algorithm:       'EC P-256',
    attestationType: 'SecureEnclave',
    createdAt:       '2024-01-15T10:22:00Z',
    lastUsedAt:      '2025-03-10T08:14:33Z',
    isHardwareBacked: true,
  },
  status:          'active',
  trustScore:      94,
  credentialCount: 7,
  issuerCount:     5,
  createdAt:       '2024-01-15T10:20:00Z',
  updatedAt:       '2025-03-10T08:14:33Z',
};

// ─── Mock issuers ─────────────────────────────────────────────────────────────

export const MOCK_ISSUERS: Record<string, Issuer> = {
  iitb: {
    id:         'iitb',
    did:        'did:sov:IIT-Bombay-0xA1B2C3',
    name:       'Indian Institute of Technology Bombay',
    shortName:  'IIT Bombay',
    logoEmoji:  '🎓',
    category:   'University',
    country:    'IN',
    isVerified: true,
    trustState: 'verified',
    addedAt:    '2024-01-20T00:00:00Z',
  },
  uidai: {
    id:         'uidai',
    did:        'did:sov:UIDAI-GOV-0xD4E5F6',
    name:       'Unique Identification Authority of India',
    shortName:  'UIDAI',
    logoEmoji:  '🇮🇳',
    category:   'Government',
    country:    'IN',
    isVerified: true,
    trustState: 'trusted',
    addedAt:    '2024-01-22T00:00:00Z',
  },
  aws: {
    id:         'aws',
    did:        'did:sov:Amazon-AWS-0xG7H8I9',
    name:       'Amazon Web Services',
    shortName:  'AWS',
    logoEmoji:  '☁️',
    category:   'Corporate',
    country:    'US',
    isVerified: true,
    trustState: 'verified',
    addedAt:    '2024-03-01T00:00:00Z',
  },
  acm: {
    id:         'acm',
    did:        'did:sov:ACM-0xJ1K2L3',
    name:       'Association for Computing Machinery',
    shortName:  'ACM',
    logoEmoji:  '⚙️',
    category:   'Professional Body',
    country:    'US',
    isVerified: true,
    trustState: 'trusted',
    addedAt:    '2024-04-10T00:00:00Z',
  },
  anthropic: {
    id:         'anthropic',
    did:        'did:sov:Anthropic-0xM4N5O6',
    name:       'Anthropic Inc.',
    shortName:  'Anthropic',
    logoEmoji:  '🤖',
    category:   'Corporate',
    country:    'US',
    isVerified: true,
    trustState: 'verified',
    addedAt:    '2025-01-10T00:00:00Z',
  },
};

// ─── Mock credentials ─────────────────────────────────────────────────────────

const BASE_CREDS: Credential[] = [
  {
    id:                 'cred-001',
    type:               'EducationCredential',
    title:              'B.Tech Computer Science',
    description:        'Bachelor of Technology in Computer Science & Engineering',
    subjectDid:         MOCK_IDENTITY.did,
    issuerDid:          MOCK_ISSUERS.iitb.did,
    issuerId:           'iitb',
    issuedAt:           '2022-05-14T00:00:00Z',
    expiresAt:          null,
    status:             'active',
    trustState:         'verified',
    signatureAlgorithm: 'Ed25519Signature2020',
    proofHash:          'a3f2b1c9d0e4f7a8b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6',
    isVerified:         true,
    rawJwt:             null,
    createdAt:          '2024-01-20T12:00:00Z',
    updatedAt:          '2024-01-20T12:00:00Z',
  },
  {
    id:                 'cred-002',
    type:               'IdentityCredential',
    title:              'Aadhaar KYC',
    description:        'Government-issued identity credential via UIDAI Aadhaar bridge',
    subjectDid:         MOCK_IDENTITY.did,
    issuerDid:          MOCK_ISSUERS.uidai.did,
    issuerId:           'uidai',
    issuedAt:           '2023-01-09T00:00:00Z',
    expiresAt:          '2033-01-09T00:00:00Z',
    status:             'active',
    trustState:         'trusted',
    signatureAlgorithm: 'Ed25519Signature2020',
    proofHash:          'b4e3c2d1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2',
    isVerified:         true,
    rawJwt:             null,
    createdAt:          '2024-01-22T09:00:00Z',
    updatedAt:          '2024-01-22T09:00:00Z',
  },
  {
    id:                 'cred-003',
    type:               'ProfessionalCredential',
    title:              'AWS Solutions Architect',
    description:        'AWS Certified Solutions Architect — Professional (SAP-C02)',
    subjectDid:         MOCK_IDENTITY.did,
    issuerDid:          MOCK_ISSUERS.aws.did,
    issuerId:           'aws',
    issuedAt:           '2023-08-22T00:00:00Z',
    expiresAt:          '2026-08-22T00:00:00Z',
    status:             'active',
    trustState:         'verified',
    signatureAlgorithm: 'Ed25519Signature2020',
    proofHash:          'c5f4d3e2b1a0c9b8a7d6e5f4c3b2a1d0e9f8c7b6a5d4e3',
    isVerified:         true,
    rawJwt:             null,
    createdAt:          '2024-03-01T14:00:00Z',
    updatedAt:          '2024-03-01T14:00:00Z',
  },
  {
    id:                 'cred-004',
    type:               'MembershipCredential',
    title:              'ACM Member 2025',
    description:        'Annual ACM professional membership credential',
    subjectDid:         MOCK_IDENTITY.did,
    issuerDid:          MOCK_ISSUERS.acm.did,
    issuerId:           'acm',
    issuedAt:           '2025-01-01T00:00:00Z',
    expiresAt:          '2026-01-01T00:00:00Z',
    status:             'active',
    trustState:         'pending',
    signatureAlgorithm: 'JsonWebSignature2020',
    proofHash:          'd6a5e4f3c2b1a0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4',
    isVerified:         false,
    rawJwt:             null,
    createdAt:          '2025-01-02T08:00:00Z',
    updatedAt:          '2025-01-02T08:00:00Z',
  },
  {
    id:                 'cred-005',
    type:               'ProfessionalCredential',
    title:              'Employment — Anthropic',
    description:        'Verified employment credential issued by Anthropic Inc.',
    subjectDid:         MOCK_IDENTITY.did,
    issuerDid:          MOCK_ISSUERS.anthropic.did,
    issuerId:           'anthropic',
    issuedAt:           '2025-01-15T00:00:00Z',
    expiresAt:          null,
    status:             'active',
    trustState:         'verified',
    signatureAlgorithm: 'Ed25519Signature2020',
    proofHash:          'e7b6f5a4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5',
    isVerified:         true,
    rawJwt:             null,
    createdAt:          '2025-01-16T10:00:00Z',
    updatedAt:          '2025-01-16T10:00:00Z',
  },
];

export const MOCK_CREDENTIALS: CredentialWithIssuer[] = BASE_CREDS.map(c => ({
  ...c,
  issuer: MOCK_ISSUERS[c.issuerId],
}));